<?php
$videos = [
    [
        'id' => 1,
        'title' => 'Building a Full-Stack App with Next.js 14',
        'channel' => 'Fireship',
        'channel_avatar' => '#FF5722',
        'views' => '890K views',
        'time' => '3 days ago',
        'duration' => '8:24',
        'thumbnail_bg' => '#1a1a2e',
    ],
    [
        'id' => 2,
        'title' => 'The Future of AI in 2026 — What Nobody Is Talking About',
        'channel' => 'AI Explained',
        'channel_avatar' => '#4CAF50',
        'views' => '1.2M views',
        'time' => '1 week ago',
        'duration' => '22:15',
        'thumbnail_bg' => '#16213e',
    ],
    [
        'id' => 3,
        'title' => 'Lo-Fi Beats to Code To — 3 Hour Mix',
        'channel' => 'Chillhop Music',
        'channel_avatar' => '#9C27B0',
        'views' => '5.6M views',
        'time' => '3 months ago',
        'duration' => '3:00:42',
        'thumbnail_bg' => '#0f3460',
    ],
    [
        'id' => 4,
        'title' => 'I Tried Every JavaScript Framework — Here\'s the Winner',
        'channel' => 'Theo - t3.gg',
        'channel_avatar' => '#FF9800',
        'views' => '2.4M views',
        'time' => '5 days ago',
        'duration' => '18:33',
        'thumbnail_bg' => '#533483',
    ],
    [
        'id' => 5,
        'title' => 'React 19 Deep Dive: Server Components Explained',
        'channel' => 'Jack Herrington',
        'channel_avatar' => '#2196F3',
        'views' => '430K views',
        'time' => '2 weeks ago',
        'duration' => '35:10',
        'thumbnail_bg' => '#1a1a2e',
    ],
    [
        'id' => 6,
        'title' => 'Learning Rust in 30 Days — Day 1 to Day 30',
        'channel' => 'No Boilerplate',
        'channel_avatar' => '#795548',
        'views' => '780K views',
        'time' => '1 month ago',
        'duration' => '45:22',
        'thumbnail_bg' => '#16213e',
    ],
    [
        'id' => 7,
        'title' => 'The Ultimate Vim Setup for 2026',
        'channel' => 'ThePrimeagen',
        'channel_avatar' => '#E91E63',
        'views' => '1.5M views',
        'time' => '2 months ago',
        'duration' => '12:47',
        'thumbnail_bg' => '#0f3460',
    ],
    [
        'id' => 8,
        'title' => 'How HTTPS Works — A Visual Guide',
        'channel' => 'ByteByteGo',
        'channel_avatar' => '#00BCD4',
        'views' => '3.1M views',
        'time' => '4 months ago',
        'duration' => '16:05',
        'thumbnail_bg' => '#533483',
    ],
    [
        'id' => 9,
        'title' => 'Building a Game Engine from Scratch in C',
        'channel' => 'jdh',
        'channel_avatar' => '#607D8B',
        'views' => '920K views',
        'time' => '1 week ago',
        'duration' => '28:59',
        'thumbnail_bg' => '#1a1a2e',
    ],
    [
        'id' => 10,
        'title' => 'Why Your Docker Setup Is Slow (And How to Fix It)',
        'channel' => 'DevOps Toolbox',
        'channel_avatar' => '#8BC34A',
        'views' => '340K views',
        'time' => '6 days ago',
        'duration' => '14:20',
        'thumbnail_bg' => '#16213e',
    ],
    [
        'id' => 11,
        'title' => 'Database Design Tips Every Developer Should Know',
        'channel' => 'Hussein Nasser',
        'channel_avatar' => '#FFC107',
        'views' => '670K views',
        'time' => '3 weeks ago',
        'duration' => '52:18',
        'thumbnail_bg' => '#0f3460',
    ],
    [
        'id' => 12,
        'title' => 'I Built the Same App with 10 Different Backends',
        'channel' => 'Beyond Fireship',
        'channel_avatar' => '#FF5722',
        'views' => '2.1M views',
        'time' => '1 month ago',
        'duration' => '19:41',
        'thumbnail_bg' => '#533483',
    ],
];

$categories = [
    'All', 'Music', 'Gaming', 'News', 'Live',
    'Computer Programming', 'Podcasts', 'Recently uploaded', 'Watched',
];
